Fix end of previous line wrongly being included in highlight
zkat/miette pull request #52
Opened 2021-09-12 15:08 UTC by icewind1991

when the highlight span starts at the very begining of a line, the highlight currently includes the line above

Before:

![image](https://user-images.githubusercontent.com/1283854/132992741-b8b45eb7-4a44-46fe-a508-facfae4a62d5.png)

After:

![image](https://user-images.githubusercontent.com/1283854/132992745-819ac7cc-fe15-4d12-b1f3-d2b75223afbb.png)

2021-09-12 17:47 UTC, zkat commented
oh sweet. Nice catch!

2021-09-12 17:56 UTC, zkat commented
ugh, looks like this does break some tests. These rules have been really tricky to get right :(

2021-09-12 19:45 UTC, icewind1991 commented
Fixed the tests, the changes in highlight border box changed the frame width

2021-09-12 21:12 UTC, zkat approved these changes

2021-09-12 21:14 UTC, zkat requested changes
The headers you changed all have to be 80 characters long, because they're meant to span the entire width of the terminal. Something funky's going on if they're 7 characters shorter now. Can you look into that?

2021-09-13 00:26 UTC, zkat commented
Nevermind that part is my fault. Can you remove the diffs on the headers and I'll just merge this? And can you add a test that covers this corner case?

2021-09-13 16:52 UTC, icewind1991 commented
done

2021-09-13 16:57 UTC, merged